# .air.toml

root    = "."
tmp_dir = "tmp"

[build]
  cmd         = "go build -o ./tmp/main ."
  bin         = "./tmp/main"

  include_ext = ["go"]          # add more if you use templates/etc.
  exclude_dir = ["tmp", "vendor"]

  poll        = true           # flip to true if you’re on Docker/WSL/NFS
  delay       = 1000            # ms debounce before rebuilding
  stop_on_error = true

[log]
  time = true

[color]
  main    = "magenta"
  watcher = "cyan"
  build   = "yellow"
  runner  = "green"

[misc]
  clean_on_exit = true
